### ISSUE TITLE
compile error under manjaro!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [chrismile/LineVis#5]
[  1%] Linking CXX shared library libsgld.so
/usr/bin/ld: /usr/local/lib/libtinyxml2.a(tinyxml2.cpp.o): warning: relocation against `_ZN8tinyxml27XMLUtil14writeBoolFalseE' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libtinyxml2.a(tinyxml2.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN8tinyxml27XMLUtil13writeBoolTrueE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sgl.dir/build.make:2248: libsgld.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sgl.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by chrismile** [comment]
Hi,

I installed a Manjaro VM, and unfortunately was not able to reproduce the error. I assume you compiled a custom version of tinyxml2? I assume that is the case, as the library lies in `/usr/local/lib/libtinyxml2.a` in your case, while the version installed via Pacman on my system lies in `/usr/lib/libtinyxml2.so.10`.

From the error message, it seems like your custom built version of tinyxml2 was built in such a way that it cannot be linked with a shared library (in the case of LineVis this is libsgl). You should get LineVis to work when you either remove your custom version of tinyxml2, or recompile your version of tinyxml2 with the `-fPIC` flag.
